# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
## main branch config starts here
- package-ecosystem: "github-actions"
  directory: "/" # Location of package manifests
  schedule:
    interval: "monthly"
    day: "friday"
  target-branch: main
  ## group all action bumps into single PR
  groups:
    all-github-actions:
      patterns: ["*"]
  commit-message:
    prefix: ":seedling:"
  labels:
  - "ok-to-test"

## main branch config ends here
