name: build-images-action

on:
  push:
    branches:
    - 'main'

permissions: {}

jobs:
  build:
    name: Build container images
    runs-on: ubuntu-latest

    permissions:
      contents: read

    if: github.repository == 'metal3-io/utility-images'
    steps:
    - name: build ipxe-builder image
      uses: toptal/jenkins-job-trigger-action@137fff703dd260b52b53d3ba1960396415abc568 # 1.0.2
      with:
        jenkins_url: "https://jenkins.nordix.org/"
        jenkins_user: "metal3.bot@gmail.com"
        jenkins_token: ${{ secrets.JENKINS_TOKEN }}
        job_name: "metal3_ipxe-builder_container_image_building"
        job_params: |
          {
            "BUILD_CONTAINER_IMAGE_GIT_REFERENCE": "${{ github.ref }}"
          }
        job_timeout: "1000"
    - name: Slack Notification on Failure
      if: ${{ failure() }}
      uses: rtCamp/action-slack-notify@4e5fb42d249be6a45a298f3c9543b111b02f7907 # 2.3.0
      env:
        SLACK_TITLE: 'GitHub Action Failed in ${{ github.repository }}'
        SLACK_COLOR: '#FF0000'
        SLACK_MESSAGE: 'The GitHub Action workflow has failed during the build of utility images.'
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_CHANNEL: metal3-github-actions-notify
        SLACK_USERNAME: metal3-github-actions-notify
